version: "3.9"
services:
  mongo:
    image: mongo
    container_name: "meme-generator-database"
    ports:
      - 5553:27017
    restart: unless-stopped
  mongo-seed:
    build:
      context: .
      dockerfile: Dockerfile.database
    links:
      - mongo
  backend:
    container_name: "meme-generator-backend"
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 5554:3000
    restart: unless-stopped
    environment:
      MONGO_HOST: "meme-generator-database:27017"
      APP_PORT: 3000
  frontend:
    container_name: "meme-generator-frontend"
    # setup nginx for react router
    volumes:
      - ./development_assets/deployment/nginx/sites-available/omm-mg-react-docker.conf:/etc/nginx/conf.d/default.conf
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_API_HOST: "http://localhost:5554"
        PUBLIC_URL: "http://localhost:5555"
    ports:
      - 5555:80
    restart: unless-stopped
